### PR TITLE
Provide a strawman set of coordination points

### LINKED ISSUE #18: What other groups need coordination
QUIC ? HTTP ? WebRTC ?  W3C (#17) ?

The charter should list those groups that will need to be consulted about solutions.

### PR DESCRIPTION
**Pull request by SpencerDawkins**
closes #18

### CODE REVIEW

**Comment by SpencerDawkins** [comment]
@mjoras and @ihlar - my apologies - I didn't request reviews for this PR when I submitted it.

**Comment by fluffy** [comment]
I do think we need to add something like this and looks like a fine start.

**Comment by SpencerDawkins** [comment]
Probably add TSVWG for discussions about host-network signaling. 
Probably add CCWG for potential self-throttling congestion controllers

**Comment by SpencerDawkins** [comment]
@SpencerDawkins, @mjoras, and @ihlar reviewed this PR on our coordination call.

**Pull request merged**
